version: "3.9"

services:
  nginx:
    build: ./nginx/
    ports:
      - 80:80

    volumes:
      - .:/var/www/html/

  php:
    build: .
    expose:
      - 9000
    env_file:
      - .env
    volumes:
      - .:/var/www/html/

  db:
    image: mariadb
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: task_management_db


volumes:
  mysql-data:
